// Generated by ReScript, PLEASE EDIT WITH CARE


function h(tag, attributesOpt, children) {
  let attributes = attributesOpt !== undefined ? attributesOpt : /* [] */0;
  return {
    TAG: "Node",
    tag: tag,
    attributes: attributes,
    children: children
  };
}

function text(str) {
  return {
    TAG: "Text",
    _0: str
  };
}

function diffOne(old, $$new) {
  if (old.TAG === "Node") {
    if ($$new.TAG === "Node") {
      if (old.tag !== $$new.tag) {
        return {
          TAG: "Replace",
          _0: $$new
        };
      } else {
        return {
          TAG: "Modify",
          remove: /* [] */0,
          set: /* [] */0
        };
      }
    } else {
      return "Nothing";
    }
  }
  let text_old = old._0;
  if ($$new.TAG === "Node") {
    return "Nothing";
  }
  let text_new = $$new._0;
  if (text_old === text_new) {
    return "Nothing";
  } else {
    return {
      TAG: "Replace",
      _0: $$new
    };
  }
}

export {
  h,
  text,
  diffOne,
}
/* No side effect */
