// Generated by ReScript, PLEASE EDIT WITH CARE


function listener(event) {
  let target = event.currentTarget;
  if (target === null) {
    return;
  }
  let ui = target._ui;
  let handler = ui.listeners[event.type];
  if (handler !== undefined) {
    return handler(event);
  }
}

function setListener(el, eventType, handle) {
  let ui = el._ui;
  if (!(eventType in ui.listeners)) {
    el.addEventListener(eventType, listener);
  }
  ui.listeners[eventType] = handle;
}

function setEmptyListeners(el) {
  let listeners = {};
  let ui = {
    listeners: listeners
  };
  el._ui = ui;
}

function eventName(str) {
  if (str.startsWith("on")) {
    return str.slice(2).toLowerCase();
  }
}

export {
  listener,
  setListener,
  setEmptyListeners,
  eventName,
}
/* No side effect */
