// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getListeners(event) {
  let target = event.currentTarget;
  if (target !== null) {
    return target._ui.listeners;
  } else if (target === null) {
    return;
  } else {
    return Primitive_option.some(target);
  }
}

function listener(event) {
  let listeners = getListeners(event);
  if (listeners !== undefined) {
    let handler = listeners[event.type];
    if (handler !== undefined) {
      handler(event);
    }
  }
}

function setListener(el, event, handle) {
  let listeners = getListeners(event);
  let listener_event = listeners !== undefined ? listeners[event.type] : listeners;
  if (listener_event !== undefined) {
    
  } else {
    el.addEventListener(event.type, listener);
  }
  let listeners$1 = getListeners(event);
  if (listeners$1 !== undefined) {
    listeners$1[event.type] = handle;
  }
}

export {
  getListeners,
  listener,
  setListener,
}
/* No side effect */
