// Generated by ReScript, PLEASE EDIT WITH CARE


let props = new Set([
  "accept",
  "acceptCharset",
  "accessKey",
  "action",
  "align",
  "alt",
  "autoplay",
  "checked",
  "cite",
  "contentEditable",
  "controls",
  "coords",
  "default",
  "dir",
  "download",
  "dropzone",
  "enctype",
  "headers",
  "hidden",
  "href",
  "hreflang",
  "htmlFor",
  "id",
  "kind",
  "label",
  "lang",
  "loop",
  "max",
  "method",
  "min",
  "name",
  "pattern",
  "ping",
  "placeholder",
  "poster",
  "preload",
  "scope",
  "selected",
  "shape",
  "span",
  "spellcheck",
  "src",
  "srcdoc",
  "srclang",
  "sandbox",
  "start",
  "step",
  "target",
  "title",
  "type",
  "useMap",
  "value",
  "wrap"
]);

function setProperty(prop, value, el) {
  if (props.has(prop)) {
    el[prop] = value;
  } else {
    el.setAttribute(prop, value);
  }
}

export {
  props,
  setProperty,
}
/* props Not a pure module */
