// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vdom from "./vdom.res.js";

let app = document.getElementById("app");

let currentVdom = {
  contents: undefined
};

let initialVdom = Vdom.h("div", {
  id: "counter",
  class: "container"
}, [
  Vdom.h("h1", undefined, [Vdom.text("Counter App")]),
  Vdom.h("button", {
    onClick: _event => {
      console.log("Increment button clicked!");
    }
  }, [Vdom.text("Increment")]),
  Vdom.h("p", undefined, [Vdom.text("Count: 0")])
]);

let domElement = Vdom.create(initialVdom);

app.appendChild(domElement);

currentVdom.contents = initialVdom;

let updatedVdom = Vdom.h("div", {
  id: "counter",
  class: "container",
  style: "color: blue;"
}, [
  Vdom.h("h1", undefined, [Vdom.text("Counter App - Updated")]),
  Vdom.h("button", {
    onClick: _event => {
      console.log("Increment button clicked!");
    }
  }, [Vdom.text("Increment")]),
  Vdom.h("p", undefined, [Vdom.text("Count: 1")])
]);

function applyDiffHandler(_event) {
  console.log("Applying diff...");
  let current = currentVdom.contents;
  if (current !== undefined) {
    let diff = Vdom.diffOne(current, updatedVdom);
    if (typeof diff !== "object") {
      console.log("No modifications needed");
      return;
    }
    if (diff.TAG === "Modify") {
      let rootElement = app.querySelector("div#counter");
      if (rootElement !== null) {
        console.log("Modifying element...");
        Vdom.modify(rootElement, diff.remove, diff.set);
        currentVdom.contents = updatedVdom;
        console.log("Diff applied successfully!");
      } else {
        console.error("Root element not found!");
      }
      return;
    }
    console.log("No modifications needed");
    return;
  } else {
    console.error("Current vdom not found!");
    return;
  }
}

let applyDiffButton = Vdom.h("button", {
  style: "margin-top: 20px; padding: 10px 20px; background: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;",
  onClick: applyDiffHandler
}, [Vdom.text("Apply Diff")]);

let buttonElement = Vdom.create(applyDiffButton);

app.appendChild(buttonElement);

/* app Not a pure module */
