// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function h(tag, attributesOpt, children) {
  let attributes = attributesOpt !== undefined ? attributesOpt : [];
  return {
    TAG: "Node",
    tag: tag,
    attributes: Object.fromEntries(attributes),
    children: children
  };
}

function text(str) {
  return {
    TAG: "Text",
    _0: str
  };
}

function diffOne(old, $$new) {
  if (old.TAG === "Node") {
    if ($$new.TAG !== "Node") {
      return {
        TAG: "Replace",
        _0: $$new
      };
    }
    if (old.tag !== $$new.tag) {
      return {
        TAG: "Replace",
        _0: $$new
      };
    }
    let remove_attrs = [];
    Stdlib_Dict.forEachWithKey(old.attributes, (_attr, key) => {
      if (key in $$new.attributes) {
        remove_attrs.push(key);
        return;
      }
    });
    let set_attrs = [];
    Stdlib_Dict.forEachWithKey($$new.attributes, (attr, key) => {
      if (Primitive_object.equal(old.attributes[key], attr)) {
        set_attrs.push([
          key,
          attr
        ]);
        return;
      }
    });
    let children = diffList(old.children, $$new.children);
    return {
      TAG: "Modify",
      remove: remove_attrs,
      set: set_attrs,
      children: children
    };
  }
  let text_old = old._0;
  if ($$new.TAG === "Node") {
    return {
      TAG: "Replace",
      _0: $$new
    };
  }
  let text_new = $$new._0;
  if (text_old === text_new) {
    return "Nothing";
  } else {
    return {
      TAG: "Replace",
      _0: $$new
    };
  }
}

function diffList(old, $$new) {
  let length = Math.max(old.length, $$new.length);
  return Stdlib_Array.fromInitializer(length, i => {
    let match = old[i];
    let match$1 = $$new[i];
    if (match !== undefined) {
      if (match$1 !== undefined) {
        return diffOne(match, match$1);
      } else {
        return "Remove";
      }
    } else if (match$1 !== undefined) {
      return {
        TAG: "Create",
        _0: match$1
      };
    } else {
      return "Nothing";
    }
  });
}

function removeNode(node) {
  let parent = node.parentNode;
  if (parent !== null) {
    parent.removeChild(node);
    return;
  }
}

function apply(el, childrenDiff) {
  let children = Stdlib_Array.fromInitializer(el.childNodes.length, i => el.childNodes.item(i));
  childrenDiff.forEach((diff, i) => {
    let match = children[i];
    if (typeof diff !== "object" && diff === "Remove" && match !== undefined) {
      return removeNode(match);
    }
  });
}

export {
  h,
  text,
  diffOne,
  diffList,
  removeNode,
  apply,
}
/* No side effect */
