// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";

function h(tag, attributesOpt, children) {
  let attributes = attributesOpt !== undefined ? attributesOpt : ({});
  return {
    TAG: "ElementNode",
    tag: tag,
    attributes: attributes,
    children: children
  };
}

function text(str) {
  return {
    TAG: "TextNode",
    _0: str
  };
}

function diffOne(l, r) {
  if (l.TAG === "ElementNode") {
    if (r.TAG !== "ElementNode") {
      return {
        TAG: "Replace",
        _0: r
      };
    }
    if (l.tag !== r.tag) {
      return {
        TAG: "Replace",
        _0: r
      };
    }
    let remove = [];
    Stdlib_Dict.forEachWithKey(l.attributes, (v, k) => {
      let match = r.attributes[k];
      if (match !== undefined) {
        return;
      } else {
        remove.push(v);
        return;
      }
    });
    let set = {};
    Stdlib_Dict.forEachWithKey(r.attributes, (rv, k) => {
      let lv = l.attributes[k];
      if (lv !== undefined && lv === rv) {
        return;
      } else {
        set[k] = rv;
        return;
      }
    });
    let children = [];
    return {
      TAG: "Modify",
      remove: remove,
      set: set,
      children: children
    };
  }
  let tl = l._0;
  if (r.TAG === "ElementNode") {
    return {
      TAG: "Replace",
      _0: r
    };
  }
  let tr = r._0;
  if (tl === tr) {
    return "Nothing";
  } else {
    return {
      TAG: "Replace",
      _0: r
    };
  }
}

function diffList(ls, rs) {
  let length = Math.max(ls.length, rs.length);
  let changeList = [];
  for (let i = 0; i < length; ++i) {
    let match = ls[i];
    let match$1 = rs[i];
    if (match !== undefined) {
      if (match$1 !== undefined) {
        changeList.push(diffOne(match, match$1));
      } else {
        changeList.push("Remove");
      }
    } else if (match$1 !== undefined) {
      changeList.push({
        TAG: "Create",
        _0: match$1
      });
    }
  }
}

function testStuff() {
  return h("div", undefined, [
    h("h2", undefined, [{
        TAG: "TextNode",
        _0: "Game Paused"
      }]),
    h("button", undefined, [{
        TAG: "TextNode",
        _0: "Game Paused"
      }]),
    h("button", undefined, [{
        TAG: "TextNode",
        _0: "Game Paused"
      }])
  ]);
}

function apply(el, childrenDiff) {
  let children = Array.from(el.children);
  childrenDiff.forEach((diff, i) => {
    if (typeof diff === "object") {
      return;
    }
    if (diff !== "Remove") {
      return;
    }
    let child = children[i];
    if (child !== undefined) {
      child.remove();
      return;
    }
  });
}

export {
  h,
  text,
  diffOne,
  diffList,
  testStuff,
  apply,
}
/* No side effect */
