// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Listeners from "./listeners.res.js";
import * as Properties from "./properties.res.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function h(tag, propertiesOpt, children) {
  let properties = propertiesOpt !== undefined ? propertiesOpt : ({});
  return {
    TAG: "ElementNode",
    tag: tag,
    properties: properties,
    children: children
  };
}

function text(str) {
  return {
    TAG: "TextNode",
    _0: str
  };
}

function diffOne(l, r) {
  if (l.TAG === "ElementNode") {
    if (r.TAG !== "ElementNode") {
      return {
        TAG: "Replace",
        _0: r
      };
    }
    if (l.tag !== r.tag) {
      return {
        TAG: "Replace",
        _0: r
      };
    }
    let remove = [];
    Stdlib_Dict.forEachWithKey(l.properties, (_v, k) => {
      let match = r.properties[k];
      if (match !== undefined) {
        return;
      } else {
        remove.push(k);
        return;
      }
    });
    let set = {};
    Stdlib_Dict.forEachWithKey(r.properties, (rv, k) => {
      let lv = l.properties[k];
      if (lv !== undefined && Primitive_object.equal(Primitive_option.valFromOption(lv), rv)) {
        return;
      } else {
        set[k] = rv;
        return;
      }
    });
    return {
      TAG: "Modify",
      remove: remove,
      set: set
    };
  }
  let tl = l._0;
  if (r.TAG === "ElementNode") {
    return {
      TAG: "Replace",
      _0: r
    };
  }
  let tr = r._0;
  if (tl === tr) {
    return "Nothing";
  } else {
    return {
      TAG: "Replace",
      _0: r
    };
  }
}

function diffList(ls, rs) {
  let length = Math.max(ls.length, rs.length);
  let changeList = [];
  for (let i = 0; i < length; ++i) {
    let match = ls[i];
    let match$1 = rs[i];
    if (match !== undefined) {
      if (match$1 !== undefined) {
        changeList.push(diffOne(match, match$1));
      } else {
        changeList.push("Remove");
      }
    } else if (match$1 !== undefined) {
      changeList.push({
        TAG: "Create",
        _0: match$1
      });
    }
  }
  return changeList;
}

function create(vnode) {
  if (vnode.TAG !== "ElementNode") {
    return document.createTextNode(vnode._0);
  }
  let el = document.createElement(vnode.tag);
  Listeners.setEmptyListeners(el);
  Stdlib_Dict.forEachWithKey(vnode.properties, (value, key) => {
    let event = Listeners.eventName(key);
    if (event !== undefined) {
      return Listeners.setListener(el, event, value);
    } else {
      return Properties.setProperty(key, value, el);
    }
  });
  vnode.children.forEach(vNodeChild => {
    let child = create(vNodeChild);
    el.appendChild(child);
  });
  return el;
}

function modify(el, remove, set) {
  remove.forEach(prop => {
    let event = Listeners.eventName(prop);
    if (event !== undefined) {
      let ui = el._ui;
      Stdlib_Dict.$$delete(ui.listeners, event);
      el.removeEventListener(event, Listeners.listener);
      return;
    }
    el.removeAttribute(prop);
  });
  Stdlib_Dict.forEachWithKey(set, (value, prop) => {
    let event = Listeners.eventName(prop);
    if (event !== undefined) {
      return Listeners.setListener(el, event, value);
    } else {
      return Properties.setProperty(prop, value, el);
    }
  });
}

function apply(el, childrenDiff) {
  let children = Array.from(el.children);
  childrenDiff.forEach((diff, i) => {
    if (typeof diff !== "object") {
      if (diff !== "Remove") {
        return;
      }
      let child = children[i];
      if (child !== undefined) {
        child.remove();
        return;
      } else {
        return;
      }
    } else {
      switch (diff.TAG) {
        case "Create" :
          let child$1 = create(diff._0);
          el.appendChild(child$1);
          return;
        case "Replace" :
          let child$2 = create(diff._0);
          let old_child = children[i];
          if (old_child !== undefined) {
            old_child.replaceWith(child$2);
            return;
          } else {
            return;
          }
        case "Modify" :
          let child$3 = children[i];
          if (child$3 !== undefined) {
            return modify(child$3, diff.remove, diff.set);
          } else {
            return;
          }
      }
    }
  });
}

export {
  h,
  text,
  diffOne,
  diffList,
  create,
  modify,
  apply,
}
/* Properties Not a pure module */
